services:
  backend:
    container_name: backend
    image: project-backend:latest
    pull_policy: never
    restart: unless-stopped
    ports:
    - 8000:8000
  frontend:
    container_name: frontend
    image: project-frontend:latest
    pull_policy: never
    restart: unless-stopped
    ports:
    - 3000:3000
